### ISSUE TITLE
Add options for ssl skip verify and proxy support as in yt-dlp

### ISSUE THREAD

**Issue by david-guenault** [shun-liang/yt2doc#65]
i'm facing a problem with ssl validation when yt2doc is launched behind proxy with ssl interception. yt-dlp allow to workaround this problem with some additional parameters

yt-dlp --compat-options no-certifi --proxy http://[hots]:[port] [video url]

This would be realy nice to add those arguments to yt2doc. 

Regards

**Comment by shun-liang** [comment]
With https://github.com/shun-liang/yt2doc/releases/tag/0.3.2, you should be able to achieve this with `--yt-dlp-extra-opts`.

https://github.com/shun-liang/yt2doc?tab=readme-ov-file#extra-options-to-yt-dlp
