### ISSUE TITLE
Add --cookies option for yt-dlp

### ISSUE THREAD

**Issue by gmag11** [shun-liang/yt2doc#66]
Sometimes YT rejects to download a file without login. This can be fixed by using --cookies <cookiefile> in yt-dlp execution.

May this option be added to yt2doc command line parameters?

**Comment by shun-liang** [comment]
Probably going to ball pack this with https://github.com/shun-liang/yt2doc/issues/65 and add cli options that allows one to add extra options for yt-dlp.

**Comment by shun-liang** [comment]
With https://github.com/shun-liang/yt2doc/releases/tag/0.3.2 you can do

```bash
yt2doc --yt-dlp-extra-opts '{"cookiefile": <cookie-file-location>}' ...
```
